Public Class leab

    Private Sub leab_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        If IO.File.Exists("C:\sdgl.dat") Then

        End If
        Try
            If IO.File.Exists("C:\sdgl.dat") = True Then
                Dim read As New IO.StreamReader("C:\sdgl.dat")

                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)
                ListBox1.Items.Add(read.ReadLine)


            Else
                MsgBox("No data")
            End If
        Catch ex As Exception

        End Try



    End Sub
End Class